version: '3.1'
services:
    my-mysql:
        image: mysql:8.0.1
        environment: 
            - MYSQL_ROOT_PASSWORD=password
        volumes: 
            - /Users/abhi/Work/docker-db:/var/lib/mysql
        ports: 
            - '3306:3306'
    my-phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - 'my-mysql:db'
        ports: 
            - '8081:80'

